# Generated by Django 2.2.dev20180521165340 on 2018-05-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0003_azure'),
    ]

    operations = [
        migrations.AddField(
            model_name='azure',
            name='AZURE_update_login_flag',
            field=models.BooleanField(default=False, max_length=2),
        ),
    ]
