# Generated by Django 2.0.6 on 2018-06-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0011_auto_20180606_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenow_model',
            name='refresh_token',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicenow_model',
            name='access_token',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
