# Generated by Django 2.0.6 on 2018-06-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0012_auto_20180606_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='appredirectstate',
            name='client_id',
            field=models.CharField(default=0, max_length=512),
        ),
        migrations.AddField(
            model_name='appredirectstate',
            name='client_secret',
            field=models.CharField(default=0, max_length=512),
        ),
        migrations.AddField(
            model_name='appredirectstate',
            name='instance',
            field=models.CharField(default=0, max_length=512),
        ),
        migrations.AlterField(
            model_name='appredirectstate',
            name='state',
            field=models.CharField(default=0, max_length=512),
        ),
    ]
