"""
Django settings for yellowant_service_now project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

BASE_URL = "https://1dfc8ef2.ngrok.io"


### YellowAnt specific settings ###
# URL to obtain oauth2 access for a YA user
YA_OAUTH_URL = "https://www.yellowant.com/api/oauth2/authorize/"
#URL to receive oauth2 codes from YA for user authentication.As a developer,you
# need to provide this URL in the YA
# developer console so that YA knows exactly where to send the oauth2 codes.
YA_REDIRECT_URL = BASE_URL+"/yellowant-oauth-redirect/"

# Numerical ID generated when you register your application through the YA developer console
YA_APP_ID = os.environ.get("YA_APP_ID", 1875)
# Client ID generated from the YA developer console. Required to identify requests from this
# application to YA
YA_CLIENT_ID = os.environ.get("YA_CLIENT_ID", "TYcdqlxZwGmEeHmVAjIDA2WjyzM6LNWAXTMasIQF")
# Client secret generated from the YA developer console. Required to identify requests from this
# application to YA
YA_CLIENT_SECRET = os.environ.get("YA_CLIENT_SECRET", "S6QqwFni7i29UoSVjSFVXIPCpZgX6JPTKJrnbuYbAbNxwFE7ItU5wtZKEFIM83uqOrcKQ3UbOoO0zFUwhmyhQiDnVUG7kfgxEifnc03No7qqsoKv8EoBFlB2pjqmJy3c")
# Verification token generated from the YA developer console. This application can verify requests
#  from YA as they will
# carry the verification token
YA_VERIFICATION_TOKEN = os.environ.get("YA_VERIFICATION_TOKEN",
                                       "69V6a3Ce9z6IKxicX7rygmwiBDGIwtKbCDrxbrWy3aWBkmb2IYJ7jHczAj1dhu61nRgD8FWdYdHNdRJ21ooXfIq2UXzQJLbNC6eoa3hpyaC8fHdaTFpqIO3bAr06tlYe")

### END YellowAnt specific settings ###


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#x9q+c*t9$=buk$i@m&6e+k@m(q@uds0gd=9=3cej6u#_u=m*%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
BASE_HREF = "/"
# SECURITY WARNING: remove wildcard condition from ALLOWED_HOSTS
ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'lib.yellowant_api',

    'lib.web',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'yellowant_service_now.urls'
CORS_ORIGIN_ALLOW_ALL = True
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yellowant_service_now.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'service_now',
        'USER': "root",
        'PASSWORD': "root1234",
        'HOST': "localhost",
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
