# Generated by Django 2.0.6 on 2018-06-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppRedirectState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_integration', models.IntegerField()),
                ('state', models.CharField(default=0, max_length=512)),
                ('client_id', models.CharField(default=0, max_length=512)),
                ('client_secret', models.CharField(default=0, max_length=512)),
                ('instance', models.CharField(default=0, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Servicenow_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_integration', models.IntegerField(default=0)),
                ('access_token', models.CharField(default='default', max_length=200)),
                ('refresh_token', models.CharField(default='default', max_length=200)),
                ('update_login_flag', models.BooleanField(default=False, max_length=2)),
                ('expires_in', models.BigIntegerField(default=1000000000)),
                ('instance', models.CharField(default=0, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='UserIntegration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('yellowant_user_id', models.IntegerField()),
                ('yellowant_team_subdomain', models.CharField(max_length=256)),
                ('yellowant_integration_id', models.IntegerField(unique=True)),
                ('yellowant_integration_invoke_name', models.CharField(max_length=256)),
                ('yellowant_integration_token', models.CharField(max_length=2048)),
                ('webhook_id', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='YellowAntRedirectState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('state', models.CharField(max_length=512)),
            ],
        ),
    ]
