# Generated by Django 2.2.dev20180521165340 on 2018-05-29 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0004_azure_azure_update_login_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='azure',
            name='user_integration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yellowant_api.UserIntegration'),
        ),
        migrations.AlterField(
            model_name='azure',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
