# Generated by Django 2.0.6 on 2018-06-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0006_azure_azure_client_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='azure',
            name='user_integration',
        ),
        migrations.DeleteModel(
            name='azure',
        ),
    ]
