# Generated by Django 2.0.6 on 2018-06-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0008_servicenow_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userintegration',
            name='user',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='yellowantredirectstate',
            name='user',
            field=models.IntegerField(),
        ),
    ]
