# Generated by Django 2.0.6 on 2018-06-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0009_auto_20180604_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRedirectState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_integration', models.IntegerField()),
                ('state', models.CharField(max_length=512)),
            ],
        ),
    ]
