# Generated by Django 2.0.6 on 2018-06-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0010_appredirectstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicenow_model',
            name='user_integration',
            field=models.IntegerField(default=0),
        ),
    ]
