# Generated by Django 2.0.6 on 2018-06-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0014_userintegration_webhook_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenow_model',
            name='instance',
            field=models.CharField(default=0, max_length=512),
        ),
    ]
