# Generated by Django 2.0.6 on 2018-06-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowant_api', '0017_auto_20180612_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenow_model',
            name='expires_in',
            field=models.BigIntegerField(default=1000000000),
        ),
    ]
